# Generated by Django 5.1.3 on 2025-03-09 23:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='completed_by',
            field=models.ManyToManyField(blank=True, related_name='completed_standalone_quizzes', to=settings.AUTH_USER_MODEL),
        ),
    ]
