# Generated by Django 5.1.3 on 2025-03-04 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_auto_20250304_1152'),
    ]

    operations = [
    ]
